# Notebook du projet

## Situation initiale

In [26]:
import random
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n = 10 # nombre d'individus

In [3]:
# Liste aléatoire de 0 et de 1 de taille n, 0 pour Samsung et 1 pour Apple
X_0 = np.asarray([random.randint(0,1) for i in range(n)])

In [4]:
# Nombre de Samsung à l'état initial
S_0 = sum(X_0[i] == 0 for i in range(n))

## Chaîne de Markov S(t)

In [5]:
def nbr_samsung(X_0):
    
    """Fonction qui compte le nombre d'indivu possédant un Samsung dans une liste d'individu
       La liste doit être un numpy array"""
    
    # Nombre de Samsung dans l'ensemble des individus
    S = (np.sum(X_0 == 0))
    return int(S) 

In [6]:
nbr_samsung(X_0)

4

## Modèle 1 : Avis de la majorité des voisins

### Implémentation du processus

In [7]:
def model_1(X_0):
    
    """Implémentation de l'évolution du modèle 1
       Renvoie la liste après une étape du processus
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)
    i = np.random.choice(len(X)) # on tire un individu X_i au hasard dans la liste X
    V = np.delete(X,i)           # ensemble des voisins de l'individu X_i
    
    # Condition d'évolution de la méthode 1
    if  np.sum(V == 1) > np.sum(V == 0):            
        X[i] = 1
    else:
        X[i] = 0

    return X

In [8]:
model_1(X_0)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0])

In [9]:
def model_1_iter(X_0, t):
    
    """Fonction itérative du modèle 1
       Renvoie la liste après t étapes du processus
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)
    k = 0
    while (k<t):
        X = np.copy(model_1(X))
        k = k+1
    return X

In [10]:
model_1_iter(X_0, 7)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1])

In [11]:
def model_1_recu(X_0, t):
    
    """Fonction récursive du modèle 1
       Applique t fois le processus du modèle 1 à la même liste
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)
    
    if (t == 0):
        return X
    else:
        return model_1(model_1_recu(X,t-1))

In [12]:
model_1_recu(X_0, 9)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0])

## Modèle 2 : Avis d'un seul voisin

### Implémentation du processus

In [13]:
def model_2(X_0):
    
    """Implémentation de l'évolution du modèle 2
       Renvoie la liste après une étape du processus
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)    
    i = np.random.choice(len(X)) # on tire un individu X_i au hasard dans la liste X
    V = np.delete(X,i)           # V_i ensemble des voisins de l'individu X_i
    j = np.random.choice(len(V)) # on tire un individu X_j au hasard dans l'ensemble V_i
    
    X[i] = np.copy(V[j])
    
    return X

In [14]:
model_2(X_0)

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0])

In [15]:
def model_2_iter(X_0, t):
    
    """Fonction itérative du modèle 2
       Renvoie la liste après t étapes du processus
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)
    k = 0
    
    while (k<t):
        k = k+1
        X =np.copy(model_2(np.copy(X)))
    return X

In [16]:
model_2_iter(X_0, 7)

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0])

In [17]:
def model_2_recu(X_0, t):
    
    """Fonction récursive du modèle 1
       Applique t fois le processus du modèle 1 à la même liste
       Fonctionne avec des numpy array"""
    
    X = np.copy(X_0)
    
    if (t == 0):
        return X
    else:
        return model_2(model_2_recu(X, t-1))    

In [18]:
model_2_recu(X_0, 9)

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0])

## Temps d'atteintes des états absorbants

### Modèle 1

In [19]:
def temps_att_1(X_0):
    
    """Fonction qui calcul le nombre d'étape nécessaire pour atteindre l'un des deux états absorbants dans le modèle 1"""
    
    cpt = 0 # variable qui compte le nombre d'étapes
    X = X_0
    Z = np.zeros(len(X_0)) # état absorbant S(t)=0
    U = np.ones(len(X_0))  # état absorbant S(t)=n
    
    while ( np.array_equal(X,Z) or np.array_equal(X,U) ) == False:
        cpt = cpt + 1
        X = model_1_recu(X,1)
    return cpt

In [20]:
temps_att_1(X_0)

50

In [43]:
def esperance_T(X_0,k):
    
    if k>(len(X_0)/2):
        Esp_T = n*( np.log(n-k) + 0.5772 + np.random.normal(0,1) )
    else:
        Esp_T = n*( np.log(k) + 0.5772 + np.random.normal(0,1))

    return Esp_T

### Modèle 2

In [ ]:
def temps_att_2(X_0):
    
    """Fonction qui calcul le nombre d'étape nécessaire pour atteindre l'un des deux états absorbants dans le modèle 2"""
    
    cpt = 0 # variable qui compte le nombre d'étapes
    X = X_0
    Z = np.zeros(len(X_0)) # état absorbant S(t)=0
    U = np.ones(len(X_0))  # état absorbant S(t)=n
    
    while ( np.array_equal(X,Z) or np.array_equal(X,U) ) == False:
        cpt = cpt + 1
        X = model_2_recu(X,1)
    return cpt

In [ ]:
temps_att_2(X_0)

## Trajectoires de la chaîne de Markov S

In [ ]:
%matplotlib notebook

### Modèle 1

In [ ]:
def traj_model_1(X_0, t):

    """Fonction qui donne les t premiers éléments de la chaine de Markov S dans le modèle 1 avec pour état initial X_0"""

    S = np.zeros(t+1)
    S[0] = nbr_samsung(X_0)
    
    for i in range(1,t+1):
        X_0 = model_1_recu(X_0,1)
        S[i] = nbr_samsung(X_0)
    
    return S

In [ ]:
traj_model_1(X_0,10)

### Modèle 2

In [ ]:
def traj_model_2(X_0, t):

    """Fonction qui donne les t premiers éléments de la chaine de Markov S dans le modèle 2 avec pour état initial X_0"""

    S = np.zeros(t+1)
    S[0] = nbr_samsung(X_0)
    
    for i in range(1,t+1):
        X_0 = model_2_recu(X_0,1)
        S[i] = nbr_samsung(X_0)
    
    return S

In [ ]:
traj_model_2(X_0,10)

### Tracé des trajectoires

In [28]:
t = 10
k = nbr_samsung(X_0)

u = np.linspace(0,t,t+1)

fig = plt.figure(1,figsize=(6,6))

# On trace 3 trajectoires
plt.plot(u,traj_model_1(X_0,t),"-ro",label="modèle 1",ms=5,linewidth=1)

plt.plot(u,traj_model_2(X_0,t),"-bo",label="modèle 2",ms=5,linewidth=1) 

plt.title('Trajectoires de S(t) dans les modèles 1 et 2')
plt.xlabel('t')
plt.ylabel('S(t)')
plt.xlim(-0.5,t+1)
plt.ylim(-0.5,10.5)
plt.legend()
plt.show()

NameError: name 'traj_model_1' is not defined

<Figure size 432x432 with 0 Axes>